version: '3.8'

services:
  instafollowcomparator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    container_name: instafollowcomparator
    
  # Development service (optional)
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    container_name: instafollowcomparator-dev
    profiles: ["dev"]